In [1]:
import numpy as np
import datetime
from proj1_helpers import *
from implementations import *


y, tX, _ = load_csv_data('data/train.csv')
tX = standardize(tX)

In [12]:
lambda_ = 0.1
initial_w = np.ones(30, dtype=float)
gamma = 0.1
max_iters = 100
max_iters_SGD = 200000

# Start SGD.
start_time = datetime.datetime.now()
weights, loss = least_squares_GD(y, tX, initial_w, max_iters, gamma)
end_time = datetime.datetime.now()
exection_time = (end_time - start_time).total_seconds()
print("least_squares_GD: execution time={t:.3f} seconds".format(t=exection_time))
print("least_squares_GD: loss={t:.6f}".format(t=loss))

start_time = datetime.datetime.now()
weights, loss = least_squares_SGD(y, tX, initial_w, max_iters_SGD, gamma)
end_time = datetime.datetime.now()
exection_time = (end_time - start_time).total_seconds()
print("least_squares_SGD: execution time={t:.3f} seconds".format(t=exection_time))
print("least_squares_SGD: loss={t:.6f}".format(t=loss))

start_time = datetime.datetime.now()
weights, loss = least_squares(y, tX)
end_time = datetime.datetime.now()
exection_time = (end_time - start_time).total_seconds()
print("least_squares: execution time={t:.3f} seconds".format(t=exection_time))
print("least_squares: loss={t:.6f}".format(t=loss))
weights, loss = least_squares_SGD(y, tX, initial_w, max_iters_SGD, gamma)

start_time = datetime.datetime.now()
weights, loss = ridge_regression(y, tX, lambda_)
end_time = datetime.datetime.now()
exection_time = (end_time - start_time).total_seconds()
print("ridge_regression: execution time={t:.3f} seconds".format(t=exection_time))
print("ridge_regression: loss={t:.6f}".format(t=loss))

ValueError: shapes (2,4) and (30,1) not aligned: 4 (dim 1) != 30 (dim 0)

In [16]:
def polynomial_basis_indices(tX, degrees, indices = np.arange(tX.shape[1]), std=False):
    """
    Creates a polynomial basis from tX.

    Parameters
    ----------
    tX : np.ndarray
        Array with the samples as rows and the features as columns.
    degrees : list or int
        List (or int) with the polynomial degrees (or maximum polynomial degree)
        that should be used as basis elements.
    indices : TODO
    
    std : bool, default=False
        Standardize features of each polynomial basis element.

    Returns
    -------
    tX_poly : np.ndarray
        tX in a polynomial basis.

    Notes
    -----
    The degree 0 is the offset-vector containing just ones. When passing the
    maximum polynomial degree as an integer as 'degrees=max_degree', this
    offset-vector is automatically added to tX. If you don't want it included,
    pass 'degrees=range(1, max_degree + 1)' instead.

    Usage
    -----
    >>> tX = np.array([1, 2, 3, 4])
    >>> tX_poly = polynomial_basis(tX, [0, 1, 2])
    >>> print(tX_poly)
    [[ 1.  1.  1.]
     [ 1.  2.  4.]
     [ 1.  3.  9.]
     [ 1.  4. 16.]]

    >>> ttX = np.arange(10).reshape((2, 5))
    >>> tX_poly = polynomial_basis_indices(tX, 2, [1, 2])
    >>> print(tX_poly)
    [[ 1.  0.  1.  2.  3.  4.  1.  4.]
    [ 1.  5.  6.  7.  8.  9. 36. 49.]]

    """

    # Checking if integer was passed as 'degrees', and converting it to a list
    if isinstance(degrees, int):

        degrees = range(degrees + 1)

    # Always including the original features (degree 1) as a basis-element
    if std:

        tX_poly = standardize(tX)

    else:

        tX_poly = tX

    for deg in degrees:

        # Treating degree zero separately to avoid duplicated columns
        if deg == 0:

            tX_poly = np.column_stack((np.ones(tX.shape[0]), tX_poly))

        elif deg > 1:

            if std:

                tX_poly = np.column_stack((tX_poly, standardize(tX[:, indices]**deg)))

            else:

                tX_poly = np.column_stack((tX_poly, tX[:, indices]**deg))

    return tX_poly

In [23]:
tX = np.arange(10).reshape((2, 5))
tX_poly = polynomial_basis_indices(tX, 2, [1, 2])
print(tX_poly)

[[ 1.  0.  1.  2.  3.  4.  1.  4.]
 [ 1.  5.  6.  7.  8.  9. 36. 49.]]
